### ISSUE TITLE
orespawn crash

### ISSUE THREAD

**Issue by hopezinho** [MinecraftModDevelopment/OreSpawn#163]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from OreSpawn (orespawn)
what can i do?

**Comment by dshadowwolf** [comment]
share the full log using a github gist, hastebin or similar ?

**Comment by hopezinho** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2 (1).jar)
  CXLibraryCore (CXLibrary-1.12.1 (2).jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/18/19 9:03 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from OreSpawn (orespawn)
Caused by: java.lang.IllegalStateException: Not a JSON Object: []
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at com.mcmoddev.orespawn.data.ReplacementsRegistry.loadFile(ReplacementsRegistry.java:164)
	at com.mcmoddev.orespawn.impl.os3.OS3APIImpl$$Lambda$467/1807815191.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.mcmoddev.orespawn.impl.os3.OS3APIImpl.loadConfigFiles(OS3APIImpl.java:86)
	at com.mcmoddev.orespawn.OreSpawn.init(OreSpawn.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 325115784 bytes (310 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                  | Signature                                |
	|:----- |:------------------- |:------------------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft           | 1.12.2                   | minecraft.jar                           | None                                     |
	| LCHI  | mcp                 | 9.42                     | minecraft.jar                           | None                                     |
	| LCHI  | FML                 | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge               | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | backpack            | 3.0.2                    | Backpacks-Mod-1.12.2.jar                | None                                     |
	| LCHI  | codechickenlib      | 3.2.2.353                | CodeChickenLib-1.12.2 (1).jar           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | cxlibrary           | 1.6.1                    | CXLibrary-1.12.1 (2).jar                | None                                     |
	| LCHI  | damageindicatorsmod | 1.0                      | Damage-Indicators-Mod-1.12.2.jar        | None                                     |
	| LCHI  | inventorytweaks     | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2 (1).jar     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | journeymap          | 1.12.2-5.5.2             | JourneyMap-Mod-1.12.2-Unlimited (1).jar | None                                     |
	| LCHI  | morefurnaces        | 1.10.1                   | More-Furnaces-Mod-1.12.1 (1).jar        | None                                     |
	| LCHE  | orespawn            | 3.3.1                    | OreSpawn-1.12-3.3.1.172 (1).jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | twilightforest      | 3.9.888                  | Twilight-Forest-Mod-1.12.2.jar          | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2 (1).jar)
  invtweaks.forge.asm.ContainerTransformer
CXLibraryCore (CXLibrary-1.12.1 (2).jar)
  cubex2.cxlibrary.CoreModTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'

**Comment by dshadowwolf** [comment]
Bad config for OreSpawn - it looks like you might have tried using an OreSpawn 1 or 2 config. OreSpawn 3 configs are "objects" - that is, the start with ``{`` and end with ``}``

More specifically, the file controlling one of the key sets of data - named selections of blocks that can be replaced - has been corrupted or replaced by a corrupt file. See:
```
Caused by: java.lang.IllegalStateException: Not a JSON Object: []
at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
at com.mcmoddev.orespawn.data.ReplacementsRegistry.loadFile(ReplacementsRegistry.java:164)
```
The last line there says it was during the loading of a "replacements" file, the first says that the file was blank. These files have changed format since the original release.

**Comment by hopezinho** [comment]
i excluded all orespawn versions that i have downloaded, and i try again but doesn't work, im brazilian so my english may be wrong.
so, what can i do?

**Comment by dshadowwolf** [comment]
OreSpawn creates a lot of configs - in this case something in config/orespawn3/sysconf stayed around. I should be checking for this - getting all the error conditions is tricky.

**Comment by hopezinho** [comment]
features-default.json
known-configs.json
replacements-default.json

this is what you have in sysconf

**Comment by dshadowwolf** [comment]
if you've upgraded from a 3.1 or 3.2 series OreSpawn... hrm... from the mod-list in the crash report I'd say you can delete everything in sysconf and let it be regenerated fresh, though this will, potentially, lead to any existing 'orespawn.json' being overwritten (it shouldn't happen, but I'm making no guarantees at this point)

**Comment by hopezinho** [comment]
ok, i deleted everything in sysconf, and.. IT WORKED, thanks so much bro :D
