### ISSUE TITLE
Please fix this I need help my orespawn is not working.

### ISSUE THREAD

**Issue by bizarreavatar** [MinecraftModDevelopment/OreSpawn#178]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 1/9/21 4:56 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from OreSpawn (orespawn)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/Render
	at danger.orespawn.util.handlers.RenderHandler.registerEntityRenders(RenderHandler.java:18)
	at danger.orespawn.util.handlers.RegistryHandler.preInitRegistries(RegistryHandler.java:34)
	at danger.orespawn.OreSpawnMain.PreInit(OreSpawnMain.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.Render
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 38 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.232-1.el7.elrepo.x86_64
	Java Version: 1.8.0_265, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 341091240 bytes (325 MB) / 797442048 bytes (760 MB) up to 1864368128 bytes (1778 MB)
	JVM Flags: 2 total; -Xmx2000M -Xms128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version           | Source                                        | Signature                                |
	|:----- |:------------------ |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCH   | mcp                | 9.42              | minecraft.jar                                 | None                                     |
	| LCH   | FML                | 8.0.99.99         | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2854      | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | aquaculture        | 1.6.8             | Aquaculture-1.12.2-1.6.8.jar                  | None                                     |
	| LCH   | baubles            | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCH   | biomesoplenty      | 7.0.1.2444        | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCH   | guideapi           | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                   | None                                     |
	| LCH   | bloodmagic         | 1.12.2-2.4.3-105  | BloodMagic-1.12.2-2.4.3-105.jar               | None                                     |
	| LCH   | jei                | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCH   | chisel             | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCH   | flansmod           | 5.5.1             | Flan's Mod-1.12.2-5.5.1.jar                   | None                                     |
	| LCH   | flansmodapocalypse | 1.0               | Flan's Mod-1.12.2-5.5.1.jar                   | None                                     |
	| LCH   | cfm                | 6.3.1             | furniture-6.3.1-1.12.2.jar                    | None                                     |
	| LCH   | ironchest          | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCH   | journeymap         | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCH   | mantle             | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCH   | mocreatures        | 12.0.5            | Mo-Creatures-Mod-1.12.2.jar                   | None                                     |
	| LCE   | orespawn           | 1.0.0             | orespawnmc_1.12-development_0.2.jar           | None                                     |
	| LC    | harvestcraft       | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar               | None                                     |
	| LC    | tconstruct         | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LC    | thaumcraft         | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |

	Loaded coremods (and transformers): 
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by dshadowwolf** [comment]
While it is always good to see people reporting bugs, I'm sad to say that you've reported this in the wrong place. This issue tracker and code base is for ***MMD*** OreSpawn - a mod that is named for what it provides - Ore Spawning for other mods. We have zero relation to the mod you are trying to report an issue for.
