### ISSUE TITLE
trying to config v2 ore spawn

### ISSUE THREAD

**Issue by Kuktar** [MinecraftModDevelopment/OreSpawn#19]
the mod started up no issues. it made an orespawn.cfg in the config folder and it has one option. it says retrogen ore. I dont see the previous options for disable ore gen from minecraft and also force ore gen.

i also can not figure out were to put my json files becuase there is no more orespawn folder that gets made inside the config during startup anymore. 

thanks,.

**Comment by iLexiconn** [comment]
To disable vanilla ore gen, remove the json properties from `.minecraft/orespawn/orespawn.json`

**Comment by Kuktar** [comment]
Awesome it worked. i am about to start adding new ores from the other mods to the gen file. I just set all the ores in the vanilla .json to 0 freq and now my world spawns with ZERO ore :P it works really well! I will make sure and let everyone i see having issues know that folder exists now :P TYTY

**Comment by Kuktar** [comment]
ok so i spoke to soon. i get this error trying different ores in hand.

so i am an OP and on the Minecraft chat box says an unknown error occurred while trying to perform this operation.

the server console says. something about it not being a json array. 

[14:42:17] [Server thread/WARN]: Couldn't process command: 'addore new all'
java.lang.IllegalStateException: This is not a JSON Array.
        at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[Js
onElement.class:?]
        at mmd.orespawn.command.AddOreCommand.func_184881_a(AddOreCommand.java:8
0) ~[AddOreCommand.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.j
ava:50) ~[CmdOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.jav
a:104) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java
:83) [k.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPl
ayServer.java:913) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPl
ayServer.java:892) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(So
urceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(So
urceFile:9) [im.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.cla
ss:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
>

**Comment by Kuktar** [comment]
the command i was running was

/addore minecraft all

**Comment by iLexiconn** [comment]
Please make a new issue for the crash =)
