### ISSUE TITLE
/addore command is not working

### ISSUE THREAD

**Issue by Kuktar** [MinecraftModDevelopment/OreSpawn#20]
here is what the server reports when i try to use the addore command.

ok so i spoke to soon. i get this error trying different ores in hand.

so i am an OP and on the Minecraft chat box says an unknown error occurred while trying to perform this operation.

the server console says. something about it not being a json array.

[14:42:17] [Server thread/WARN]: Couldn't process command: 'addore new all'
java.lang.IllegalStateException: This is not a JSON Array.
at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[Js
onElement.class:?]
at mmd.orespawn.command.AddOreCommand.func_184881_a(AddOreCommand.java:8
0) ~[AddOreCommand.class:?]
at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.j
ava:50) ~[CmdOverride.class:?]
at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.jav
a:104) [k.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java
:83) [k.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPl
ayServer.java:913) [me.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPl
ayServer.java:892) [me.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(So
urceFile:37) [im.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(So
urceFile:9) [im.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.cla
ss:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_111]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [M
inecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by dshadowwolf** [comment]
OreSpawn 1 uses a json that is a "Json Object" at the top level, OreSpawn 2 is a "Json Array" at the top level. OreSpawn 3 is like OreSpawn 1, but has a format closer to that of OreSpawn 2 for the data.

This error seems to indicate that you may have tried using an OreSpawn 1 style config with OreSpawn 2 - which does not (outside of certain versions and situations) understand the OreSpawn 1 format at all.

And... sorry for the lag on responding - iLexiconn left the project before I joined the MMD Team and I've only, recently, taken over as lead coder for this project.

**Comment by jriwanek** [comment]
Should be fixed in next stable release

**Comment by dshadowwolf** [comment]
Have got some work done on this - will add for the current session, but you will have to use the /osWriteConfig command (I think thats the right one) to actually save the modifications off - which will put it in a separate directory for review and then manual inclusion

**Comment by jriwanek** [comment]
Works in 3.2.1
